[package]
name = "fischy"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"

[dependencies]
enigo = { version = "0.3.0", features = ["x11rb"] }
image = "0.25.6"
rand = "0.9.0"
xcap = "0.4.1"

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
cast_possible_wrap = "allow"
cast_sign_loss = "allow"
cast_possible_truncation =  "allow"
cast_precision_loss = "allow"
too_many_lines = "allow"
